# ----------------------------------------
#
#  File: makefile
#  Author: Myles Busig
#  Date Created: 2020-05-09
#  Last Edited: 2020-05-09
#
#  Description:
#  Provides rules for managing the potato-script project
#
#  Copyright (c) Myles Busig, 2020
#
# ----------------------------------------

# ----------------------------------------
